"""Rebuild the committed demo database, data/demo/nullpunkt-demo.db.

    python scripts/make_demo_db.py                 # briefs from the cache only (no Phi calls)
    python scripts/make_demo_db.py --allow-model   # ask Phi (Ollama) for briefs not in the cache

Steps:
1. Generate the seed-42 demo shift from configs/generator.yaml into data/generated/batch-042.
2. Prepare it (the full pipeline with briefs) into a fresh database next to the output.
3. Check it is pristine: no decisions, openings, flags or study sessions; only the
   ``shift_prepared`` audit event; every incident open.
4. Switch it out of WAL mode, compact it, and move it into place.

By default every brief must come from the brief cache (``briefing.cache_dir`` in
configs/pipeline.yaml), so rebuilding needs no model and gives the same briefs; the script stops if
one is missing. With ``--allow-model``, missing briefs are generated by Phi, which must be running.
Run from the repository root.
"""

from __future__ import annotations

import argparse
import sqlite3
import sys
from pathlib import Path

from nullpunkt.briefing.llm import LLMError, OllamaClient, OllamaSettings
from nullpunkt.core.config import load_pipeline_config
from nullpunkt.generator.batch import generate, write_batch
from nullpunkt.generator.config import load_config
from nullpunkt.storage.demo import DEFAULT_PRISTINE, pristine_problems
from nullpunkt.storage.prepare import prepare_shift
from nullpunkt.storage.repository import SQLiteRepository

BATCH_DIR = Path("data/generated/batch-042")


class CacheOnlyClient:
    """Stands in for Phi under the same model name, so cached briefs are found; it never calls a
    model. A cache miss becomes a template fallback, which the script then refuses."""

    def __init__(self, model: str) -> None:
        self.model = model

    def generate(self, system: str, user: str, schema: dict) -> str:
        raise LLMError("error", "not in the brief cache (rerun with --allow-model)")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Rebuild the committed demo database.")
    parser.add_argument(
        "--out", type=Path, default=DEFAULT_PRISTINE, help=f"output (default: {DEFAULT_PRISTINE})"
    )
    parser.add_argument(
        "--allow-model", action="store_true", help="ask Phi for briefs missing from the cache"
    )
    args = parser.parse_args(argv)

    cfg = load_pipeline_config("configs/pipeline.yaml")
    write_batch(generate(load_config("configs/generator.yaml")), BATCH_DIR)
    client = (
        OllamaClient(cfg.briefing)
        if args.allow_model
        else CacheOnlyClient(OllamaSettings().model or cfg.briefing.model)
    )

    args.out.parent.mkdir(parents=True, exist_ok=True)
    tmp = args.out.with_name(args.out.name + ".building")
    for path in (tmp, Path(f"{tmp}-wal"), Path(f"{tmp}-shm")):
        path.unlink(missing_ok=True)
    repo = SQLiteRepository(tmp)
    try:
        prepared = prepare_shift(BATCH_DIR, repo, cfg, client=client)
    finally:
        repo.close()

    briefing = prepared.result.briefing
    assert briefing is not None
    paths = briefing.paths()
    print(f"{prepared.batch.batch_id}: {prepared.batch.alert_count} alerts -> "
          f"{prepared.batch.incident_count} incidents; briefs: {paths}")  # fmt: skip
    fallbacks = [o.incident_id for o in briefing.outcomes.values() if o.fallback_used]
    if fallbacks:
        print(f"error: template briefs for {', '.join(fallbacks)}", file=sys.stderr)
        return 1

    conn = sqlite3.connect(tmp)
    conn.execute("PRAGMA journal_mode = DELETE")  # one self-contained file, no -wal side file
    conn.execute("VACUUM")
    conn.close()
    if problems := pristine_problems(tmp):
        print(f"error: {'; '.join(problems)}", file=sys.stderr)
        return 1
    tmp.replace(args.out)
    print(f"wrote {args.out} ({args.out.stat().st_size / 1e6:.1f} MB)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
